/******************************************************************************
 * Copyright 2019 ETC Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************
 * This file is a part of RDMnet. For more information, go to:
 * https://github.com/ETCLabs/RDMnet
 *****************************************************************************/

/*!
 * \file rdmnet/core/message.h
 * \brief Basic types for parsed RDMnet messages.
 */

#ifndef RDMNET_CORE_MESSAGE_H_
#define RDMNET_CORE_MESSAGE_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "etcpal/acn_rlp.h"
#include "etcpal/uuid.h"
#include "rdmnet/core/broker_prot.h"
#include "rdmnet/core/rpt_prot.h"
#include "rdmnet/core/ept_prot.h"

/*!
 * \defgroup rdmnet_message Message
 * \ingroup rdmnet_core_lib
 *
 * Types to represent RDMnet messages, and functions to pack and unpack them. LLRP Messages are
 * excluded, as they are handled by separate logic.
 *
 * @{
 */

#ifdef __cplusplus
extern "C" {
#endif

typedef enum
{
  kRptClientMsgRdmCmd,
  kRptClientMsgRdmResp,
  kRptClientMsgStatus
} rpt_client_msg_t;

/*! An RDMnet RDM command generated by a local component. */
typedef struct RdmnetLocalRdmCommand
{
  /*! The UID of the RDMnet component to which this command is addressed. */
  RdmUid rdmnet_dest_uid;
  /*!
   * The endpoint on the RDMnet component to which this command is addressed. If addressing the
   * default (root) responder of an RDMnet device, set this to E133_NULL_ENDPOINT.
   */
  uint16_t dest_endpoint;
  /*!
   * The UID of the RDM responder to which this command is addressed. If addressing the default
   * (root) responder of an RDMnet device, this should be the same as rdmnet_dest_uid.
   */
  RdmUid rdm_dest_uid;
  /*! The sub-device to which this command is addressed, or 0 for the root device. */
  uint16_t subdevice;
  /*! The command class for this command. */
  rdm_command_class_t command_class;
  /*!
   * The RDM parameter ID for this command. One of the values from E1.20 Table A-3, E1.33
   * Table A-15, or any of the relevant E1.37 extension standards.
   */
  uint16_t param_id;
  /*! The length of the parameter data. */
  uint8_t datalen;
  /*! The parameter data. */
  uint8_t data[RDM_MAX_PDL];
} RdmnetLocalRdmCommand;

/*! An RDMnet RDM command received by this component. */
typedef struct RdmnetRemoteRdmCommand
{
  /*! The UID of the component that sent this command. */
  RdmUid source_uid;
  /*! The local endpoint to which this command is addressed. */
  uint16_t dest_endpoint;
  /*! The command's sequence number, to be echoed in its response. */
  uint32_t seq_num;
  /*! The RDM command. */
  RdmCommand rdm_command;
} RdmnetRemoteRdmCommand;

/*! An RDMnet RDM response generated by this component. */
typedef struct RdmnetLocalRdmResponse
{
  /*! The UID of the RDMnet component to which this response is addressed. */
  RdmUid rdmnet_dest_uid;
  /*! The local endpoint from which this response is being sent. */
  uint16_t source_endpoint;
  /*! The sequence number from the corresponding command, or 0 for an unsolicited response. */
  uint32_t seq_num;
  /*! Whether the original command is included; if so, store it in original_command. */
  bool original_command_included;
  /*!
   * The original command associated with this response; valid if original_command_included is
   * true.
   */
  RdmCommand original_command;
  /*! The encapsulated RDM response. */
  RdmResponse rdm_response;
} RdmnetLocalRdmResponse;

/*! An RDMnet RDM response received by a local component. */
typedef struct RdmnetRemoteRdmResponse
{
  /*! The UID of the RDMnet component that sent this response. */
  RdmUid rdmnet_source_uid;
  /*! The endpoint from which the response was sent. */
  uint16_t source_endpoint;
  /*! The sequence number of the response, for matching with a corresponding command. */
  uint32_t seq_num;
  /*! Whether the original command is included; if so, it is stored in original_command. */
  bool original_command_included;
  /*!
   * The original command associated with this response; valid if original_command_included is
   * true.
   */
  RdmCommand original_command;
  /*! The encapsulated RDM response. */
  RdmResponse rdm_response;
  /*!
   * This message contains partial RDM data. This can be set when the library runs out of static
   * memory in which to store RDM response data and must deliver a partial data buffer before
   * continuing (this only applies to the data buffer within the RDM response). The application
   * should store the partial data but should not act on it until another RdmnetRemoteRdmResponse
   * is received with more_coming set to false.
   */
  bool more_coming;
} RdmnetRemoteRdmResponse;

/*! An RDMnet RPT status message generated by a local component. */
typedef struct RdmnetLocalRptStatus
{
  /*! The UID of the RDMnet component to which this status message is addressed. */
  RdmUid rdmnet_dest_uid;
  /*! The local endpoint from which this status message is being sent. */
  uint16_t source_endpoint;
  /*! The sequence number from the corresponding command. */
  uint32_t seq_num;
  /*! A status code that indicates the specific error or status condition. */
  rpt_status_code_t status_code;
  /*! An optional implementation-defined status string to accompany this status message. */
  const char* status_string;
} RdmnetLocalRptStatus;

/*! An RDMnet RPT status message received by a local component. */
typedef struct RdmnetRemoteRptStatus
{
  /*! The UID of the RDMnet component that sent this status message. */
  RdmUid rdmnet_source_uid;
  /*! The endpoint from which the status message was sent. */
  uint16_t source_endpoint;
  /*! The sequence number of the status message, for matching with a corresponding command. */
  uint32_t seq_num;
  /*! A status code that indicates the specific error or status condition. */
  rpt_status_code_t status_code;
  /*! An optional implementation-defined status string to accompany this status message. */
  const char* status_string;
} RdmnetRemoteRptStatus;

typedef struct RptClientMessage
{
  rpt_client_msg_t type;
  union
  {
    RdmnetRemoteRdmCommand cmd;
    RdmnetRemoteRdmResponse resp;
    RdmnetRemoteRptStatus status;
  } payload;
} RptClientMessage;

#define RDMNET_GET_REMOTE_RDM_COMMAND(rptclimsgptr) (&(rptclimsgptr)->payload.cmd)
#define RDMNET_GET_REMOTE_RDM_RESPONSE(rptclimsgptr) (&(rptclimsgptr)->payload.resp)
#define RDMNET_GET_REMOTE_RPT_STATUS(rptclimsgptr) (&(rptclimsgptr)->payload.status)

typedef enum
{
  kEptClientMsgData,
  kEptClientMsgStatus
} ept_client_msg_t;

typedef struct EptClientMessage
{
  ept_client_msg_t type;
  union
  {
    EptStatusMsg status;
    EptDataMsg data;
  } payload;
} EptClientMessage;

/*! An RDMnet received from one of RDMnet's TCP protocols. */
typedef struct RdmnetMessage
{
  /*! The root layer vector. Compare to the vectors in \ref acn_rootlayerpdu. */
  uint32_t vector;
  /*! The CID of the Component that sent this message. */
  EtcPalUuid sender_cid;
  /*! The encapsulated message; use the helper macros to access it. */
  union
  {
    BrokerMessage broker;
    RptMessage rpt;
    EptMessage ept;
  } data;
} RdmnetMessage;

/*!
 * \brief Determine whether an RdmnetMessage contains a Broker message.
 * \param msgptr Pointer to RdmnetMessage.
 * \return (bool) whether the message contains a Broker message.
 */
#define RDMNET_IS_BROKER_MSG(msgptr) ((msgptr)->vector == ACN_VECTOR_ROOT_BROKER)

/*!
 * \brief Get the encapsulated Broker message from an RdmnetMessage.
 * \param msgptr Pointer to RdmnetMessage.
 * \return Pointer to encapsulated Broker message (BrokerMessage*).
 */
#define RDMNET_GET_BROKER_MSG(msgptr) (&(msgptr)->data.broker)

/*!
 * \brief Determine whether an RdmnetMessage contains a RPT message.
 * \param msgptr Pointer to RdmnetMessage.
 * \return (bool) whether the message contains a RPT message.
 */
#define RDMNET_IS_RPT_MSG(msgptr) ((msgptr)->vector == ACN_VECTOR_ROOT_RPT)

/*!
 * \brief Get the encapsulated RPT message from an RdmnetMessage.
 * \param msgptr Pointer to RdmnetMessage.
 * \return Pointer to encapsulated RPT message (RptMessage*).
 */
#define RDMNET_GET_RPT_MSG(msgptr) (&(msgptr)->data.rpt)

/*!
 * \brief Determine whether an RdmnetMessage contains a EPT message.
 * \param msgptr Pointer to RdmnetMessage.
 * \return (bool) whether the message contains a EPT message.
 */
#define RDMNET_IS_EPT_MSG(msgptr) ((msgptr)->vector == ACN_VECTOR_ROOT_EPT)

/*!
 * \brief Get the encapsulated EPT message from an RdmnetMessage.
 * \param msgptr Pointer to RdmnetMessage.
 * \return Pointer to encapsulated EPT message (EptMessage*).
 */
#define RDMNET_GET_EPT_MSG(msgptr) (&(msgptr)->data.ept)

/*! An RDM command to be sent from a local LLRP Manager. */
typedef struct LlrpLocalRdmCommand
{
  /*! The CID of the LLRP Target to which this command is addressed. */
  EtcPalUuid dest_cid;
  /*! The RDM command. */
  RdmCommand rdm;
} LlrpLocalRdmCommand;

/*! An RDM command received from a remote LLRP Manager. */
typedef struct LlrpRemoteRdmCommand
{
  /*! The CID of the LLRP Mangaer from which this command was received. */
  EtcPalUuid src_cid;
  /*! The sequence number received with this command, to be echoed in the corresponding
   *  LlrpLocalRdmResponse. */
  uint32_t seq_num;
  /*! An ID for the network interface on which this command was received, to be echoed in the
   *  corresponding LlrpLocalRdmResponse. This helps the LLRP library send the response on the same
   *  interface on which it was received. */
  RdmnetMcastNetintId netint_id;
  /*! The RDM command. */
  RdmCommand rdm_command;
} LlrpRemoteRdmCommand;

/*! An RDM command to be sent from a local LLRP Target. */
typedef struct LlrpLocalRdmResponse
{
  /*! The CID of the LLRP Manager to which this response is addressed. */
  EtcPalUuid dest_cid;
  /*! The sequence number received in the corresponding LlrpRemoteRdmCommand. */
  uint32_t seq_num;
  /*! The network interface ID in the corresponding LlrpRemoteRdmCommand. */
  RdmnetMcastNetintId netint_id;
  /*! The RDM response. */
  RdmSingleResponse rdm_response;
} LlrpLocalRdmResponse;

/*! An RDM response received from a remote LLRP Target. */
typedef struct LlrpRemoteRdmResponse
{
  /*! The CID of the LLRP Target from which this command was received. */
  EtcPalUuid src_cid;
  /*! The sequence number of this response (to be associated with a previously-sent command). */
  uint32_t seq_num;
  /*! The RDM response. */
  RdmSingleResponse rdm_response;
} LlrpRemoteRdmResponse;

typedef struct RdmnetSyncRdmResponse
{
  bool ack;
  rdm_nack_reason_t nack_reason;
  size_t response_data_len;
} RdmnetSyncRdmResponse;

void rdmnet_create_response(const RdmnetRemoteRdmCommand* received_cmd, const RdmResponse* rdm_arr,
                            size_t num_responses, RdmnetLocalRdmResponse* resp);
void rdmnet_create_unsolicited_response(uint16_t source_endpoint, const RdmResponse* rdm_arr, size_t num_responses,
                                        RdmnetLocalRdmResponse* resp);
void rdmnet_create_status_with_str(const RdmnetRemoteRdmCommand* received_cmd, rpt_status_code_t status_code,
                                   const char* status_str, RdmnetLocalRptStatus* status);
void rdmnet_create_status(const RdmnetRemoteRdmCommand* received_cmd, rpt_status_code_t status_code,
                          RdmnetLocalRptStatus* status);

void rdmnet_create_llrp_response(const LlrpRemoteRdmCommand* received_cmd, const uint8_t* data, uint8_t datalen,
                                 LlrpLocalRdmResponse* resp);
void rdmnet_create_llrp_nack(const LlrpRemoteRdmCommand* received_cmd, uint16_t nack_reason,
                             LlrpLocalRdmResponse* resp);

void rdmnet_free_message_resources(RdmnetMessage* msg);

#ifdef __cplusplus
}
#endif

/*!
 * @}
 */

#endif /* RDMNET_CORE_MESSAGE_H_ */
