<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns="http://schemas.microsoft.com/wix/2006/wi"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:wix="http://schemas.microsoft.com/wix/2006/wi" xmlns:str="http://xsltsl.org/string"
    exclude-result-prefixes="wix str">

  <xsl:output encoding="utf-8" method="xml" version="1.0" indent="yes" />

  <!-- identity template -->
  <xsl:template match="@*|node()">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>

  <!-- Add a predictable file ID for the controller executable which is harvested -->
  <xsl:template match='wix:File[contains(@Source, "rdmnet_controller_example.exe")]/@Id'>
    <xsl:attribute name="Id">
      <xsl:text>ControllerExe</xsl:text>
    </xsl:attribute>
  </xsl:template>

  <xsl:template match='/'>
    <xsl:comment>*** DO NOT EDIT: Generated by heat.exe; transformed by ControllerShortcuts.xsl</xsl:comment>
    <xsl:apply-templates select="@*|node()"/>
  </xsl:template>

</xsl:stylesheet>
